name: Build and deploy

on:
  workflow_call:
    inputs:
      environment:
        type: string
      url:
        type: string
      deploy:
        type: boolean
        default: false

jobs:
  build:
    runs-on: [self-hosted, web]
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.url }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          persist-credentials: false
      - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548
        with:
          python-version: 3.9
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@30aa0023464ed4b5b116bd9fbdab87acf01a484e
      - name: Install Python libs
        run: pip3 install -r ./requirements.txt
      - uses: ruby/setup-ruby@ac793fdd38cc468a4dd57246fa9d0e868aba9085
        with:
          ruby-version: 3.2
          bundler-cache: true
      - uses: seanmiddleditch/gha-setup-ninja@3b1f8f94a2f8254bd26914c4ab9474d4f0015f67
        with:
          version: 1.10.2
      - name: Install arm-none-eabi-gcc GNU Arm Embedded Toolchain
        if: ${{ inputs.deploy }}
        uses: carlosperate/arm-none-eabi-gcc-action@4c88c61a77a39a33a7722d24a4e8b2c573f766c9
      - name: Install Doxygen
        if: ${{ inputs.deploy }}
        run: |
          wget https://www.doxygen.nl/files/doxygen-1.10.0.linux.bin.tar.gz
          if echo 'dcfc9aa4cc05aef1f0407817612ad9e9201d9bf2ce67cecf95a024bba7d39747  doxygen-1.10.0.linux.bin.tar.gz' | sha256sum --check --status
          then
            tar xf doxygen-1.10.0.linux.bin.tar.gz -C "$HOME"
            echo "$HOME/doxygen-1.10.0/bin" >> $GITHUB_PATH
          fi
      - name: Build Doxygen documentation
        if: ${{ inputs.deploy }}
        run: make build_doxygen_adoc
      - name: Build documentation
        run: make -j 2
      - name: Deploy to Mythic Beasts
        if: ${{ inputs.deploy }}
        uses: ./.github/actions/deploy-action
        with:
          private_ssh_key: ${{ secrets.DEPLOY_SSH_KEY }}
          bastion_host: ${{ secrets.DEPLOY_BASTION_HOST }}
          primary_host: ${{ secrets.DEPLOY_PRIMARY_HOST }}
          secondary_host: ${{ secrets.DEPLOY_SECONDARY_HOST }}
          source: documentation/html/
          destination: documentation
